In [1]:
import requests

API_KEY = "8b20cab3e9164b8b93bd896b642e7089"  # Reemplaza con tu key real
BASE_URL = "https://api.rawg.io/api"


url = f"{BASE_URL}/games?key={API_KEY}"
respuesta = requests.get(url)
datos = respuesta.json()

total = datos["count"]
print(f"RAWG tiene registrados {total} juegos en total.")

RAWG tiene registrados 898364 juegos en total.

In [2]:
url = f"{BASE_URL}/games?key={API_KEY}&ordering=-metacritic&page_size=5"
respuesta = requests.get(url)
datos = respuesta.json()

print("Primeros 5 juegos mejor valorados según Metacritic:\n")
for juego in datos["results"]:
    print(f"Nombre del juego: {juego['name']}")
    print(f"  Rating: {juego['rating']}")
    print(f"  Metacritic: {juego['metacritic']}")
    print()

Top 5 juegos mejor valorados según Metacritic:

Nombre: The Legend of Zelda: Ocarina of Time
  Rating: 4.38
  Metacritic: 99

Nombre: Soulcalibur (1998)
  Rating: 0.0
  Metacritic: 98

Nombre: Soulcalibur
  Rating: 4.38
  Metacritic: 98

Nombre: Baldur's Gate III
  Rating: 4.44
  Metacritic: 97

Nombre: Metroid Prime
  Rating: 4.35
  Metacritic: 97

In [5]:
url = f"{BASE_URL}/games?key={API_KEY}&stores=1&ordering=-rating&page_size=10"
respuesta = requests.get(url)
datos = respuesta.json()

print("Primeros 10 juegos en Steam:\n")
for juego in datos["results"]:
    print(f"Nombre del juego: {juego['name']}")
    print(f"  Rating: {juego['rating']}")
    print()

Primeros 10 juegos en Steam:

Nombre del juego: Warhammer 40,000: Dawn of War - Definitive Edition
  Rating: 4.83

Nombre del juego: No Case Should Remain Unsolved
  Rating: 4.83

Nombre del juego: The Witcher 3: Wild Hunt – Blood and Wine
  Rating: 4.81

Nombre del juego: The Witcher 3 Wild Hunt - Complete Edition
  Rating: 4.8

Nombre del juego: The Witcher 3: Wild Hunt – Hearts of Stone
  Rating: 4.76

Nombre del juego: Persona 5 Royal
  Rating: 4.75

Nombre del juego: Guilty Parade
  Rating: 4.71

Nombre del juego: Cyberpunk 2077: Phantom Liberty
  Rating: 4.71

Nombre del juego: The Binding of Isaac: Repentance
  Rating: 4.69

Nombre del juego: Red Matter 2
  Rating: 4.67

In [7]:
url_pc = f"{BASE_URL}/games?key={API_KEY}&platforms=4&ordering=-rating&page_size=5"
url_ps5 = f"{BASE_URL}/games?key={API_KEY}&platforms=187&ordering=-rating&page_size=5"

datos_pc = requests.get(url_pc).json()
datos_ps5 = requests.get(url_ps5).json()

print("Primeros 5 juegos en PC:")
rating_pc = []
for juego in datos_pc["results"]:
    print(f"  {juego['name']} - Rating: {juego['rating']}")
    rating_pc.append(juego["rating"])

print(f"\nPromedio rating PC: {sum(rating_pc)/len(rating_pc):.2f}")

print("\nPrimeros 5 juegos en la PS5:")
rating_ps5 = []
for juego in datos_ps5["results"]:
    print(f"  {juego['name']} - Rating: {juego['rating']}")
    rating_ps5.append(juego["rating"])

print(f"\nPromedio rating PS5: {sum(rating_ps5)/len(rating_ps5):.2f}")

if sum(rating_pc)/len(rating_pc) > sum(rating_ps5)/len(rating_ps5):
    print("\nPC tiene los juegos mejor valorados.")
else:
    print("\nResultado: PS5 tiene los juegos mejor valorados.")

Primeros 5 juegos en PC:
  The Elder Scrolls VI - Rating: 4.86
  Warhammer 40,000: Dawn of War - Definitive Edition - Rating: 4.83
  No Case Should Remain Unsolved - Rating: 4.83
  The Witcher 3: Wild Hunt – Blood and Wine - Rating: 4.81
  The Witcher 3 Wild Hunt - Complete Edition - Rating: 4.8

Promedio rating PC: 4.83

Primeros 5 juegos en la PS5:
  The Witcher 3 Wild Hunt - Complete Edition - Rating: 4.8
  Persona 5 Royal - Rating: 4.75
  Cyberpunk 2077: Phantom Liberty - Rating: 4.71
  The Binding of Isaac: Repentance - Rating: 4.69
  The Last of Us Part I - Rating: 4.67

Promedio rating PS5: 4.72

PC tiene los juegos mejor valorados.

In [9]:
import pandas as pd

# C2 - Comparar 3 juegos famosos
juegos_buscar = ["Red Dead Redemption 2", "God of War", "Minecraft"]

tabla = []

for nombre in juegos_buscar:
    url = f"{BASE_URL}/games?key={API_KEY}&search={nombre}&page_size=1"
    datos = requests.get(url).json()
    juego = datos["results"][0]
    
    generos = ", ".join([g["name"] for g in juego["genres"]])
    plataformas = ", ".join([p["platform"]["name"] for p in juego["platforms"][:3]])
    
    tabla.append({
        "Nombre": juego["name"],
        "Rating": juego["rating"],
        "Metacritic": juego["metacritic"],
        "Géneros": generos,
        "Plataformas": plataformas
    })

df = pd.DataFrame(tabla)
df

,Nombre,Rating,Metacritic,Géneros,Plataformas
0,Red Dead Redemption 2,4.59,96,Action,"PC, Xbox One, PlayStation 4"
1,God of War I,4.36,94,Action,"PlayStation 3, PlayStation 2, PS Vita"
2,Minecraft,4.44,83,"Action, Arcade, Simulation, Indie, Massively M...","PC, Xbox One, PlayStation 4"

In [10]:
generos = {
    "Action": 4,
    "RPG": 5,
    "Shooter": 2,
    "Strategy": 10
}

resultados_generos = []

for nombre_genero, genero_id in generos.items():
    url = f"{BASE_URL}/games?key={API_KEY}&genres={genero_id}&ordering=-rating&page_size=5"
    datos = requests.get(url).json()
    
    ratings = [j["rating"] for j in datos["results"]]
    promedio = sum(ratings) / len(ratings)
    
    resultados_generos.append({
        "Género": nombre_genero,
        "Promedio Rating": round(promedio, 2)
    })

df_generos = pd.DataFrame(resultados_generos)
df_generos = df_generos.sort_values("Promedio Rating", ascending=False)

print("Promedio de rating por género:\n")
print(df_generos.to_string(index=False))
print(f"\nEl género con mejor rating es: {df_generos.iloc[0]['Género']}")

Promedio de rating por género:

  Género  Promedio Rating
     RPG             4.80
  Action             4.77
Strategy             4.71
 Shooter             4.68

El género con mejor rating es: RPG

In [13]:
years = [2004, 2013, 2024]

resultados_years = []

for year in years:
    url = f"{BASE_URL}/games?key={API_KEY}&dates={year}-01-01,{year}-12-31&ordering=-metacritic&page_size=5"
    datos = requests.get(url).json()
    
    metacritics = [j["metacritic"] for j in datos["results"] if j["metacritic"]]
    promedio = sum(metacritics) / len(metacritics) if metacritics else 0
    
    resultados_years.append({
        "Año": year,
        "Promedio Metacritic": round(promedio, 2)
    })

df_years = pd.DataFrame(resultados_years)
df_years = df_years.sort_values("Promedio Metacritic", ascending=False)

print("Promedio Metacritic por año:\n")
print(df_years.to_string(index=False))
print(f"\nEl año con mejor Metacritic promedio es 2004")

Promedio Metacritic por año:

 Año  Promedio Metacritic
2004                 93.8
2013                 93.6
2024                 82.0

El año con mejor Metacritic promedio es 2004

In [14]:
import os

url = f"{BASE_URL}/games?key={API_KEY}&ordering=-rating&page_size=20"
datos = requests.get(url).json()

top20 = []

for juego in datos["results"]:
    genero_principal = juego["genres"][0]["name"] if juego["genres"] else "Sin género"
    
    top20.append({
        "name": juego["name"],
        "rating": juego["rating"],
        "metacritic": juego["metacritic"],
        "release_date": juego["released"],
        "main_genre": genero_principal
    })

df_top20 = pd.DataFrame(top20)

In [15]:
os.makedirs("output", exist_ok=True)

df_top20.to_csv("output/top20_rawg.csv", index=False)

print("Archivo guardado en output/top20_rawg.csv")
print("\nPrimeras 5 filas:\n")
df_top20.head()

Archivo guardado en output/top20_rawg.csv

Primeras 5 filas:

,name,rating,metacritic,release_date,main_genre
0,The Elder Scrolls VI,4.86,NaN,None,Action
1,"Warhammer 40,000: Dawn of War - Definitive Edi...",4.83,NaN,None,Sin género
2,No Case Should Remain Unsolved,4.83,NaN,2024-01-17,Adventure
3,Gimmick!,4.83,NaN,1992-01-31,Sin género
4,Super Robot Taisen: Original Generation,4.83,NaN,2002-11-22,Action

In [22]:
print("\n¿Qué fue lo más interesante que encontré en los datos?")
print("Me sorprendió que el año 2004 tuviera el Metacritic promedio más alto. Esto sugiere que fue una época dorada para los videojuegos. A pesar que los juegos de ahora son mejores en diseño, pero tal vez no tienen esa nostalgia que los de antes sí.")

print("\n¿Qué género o plataforma te sorprendió más y por qué?")
print("Me sorprendió que PC superara a PS5 en rating promedio (4.83 vs 4.72), esperaba que PS5 tuviera los mejores títulos por ser más moderna. Aparte que la PC no está hecho directamente para jugar, algo que la PS5 sí")


print("\n¿Qué otra pregunta le harías a esta API si tuvieras más tiempo?")
print("Me gustaría analizar si los juegos con más reseñas tienen mejor rating, o si hay alguna relación sobre el precio del juego y su reseña.")

print("\n¿Cuántas requests usé en total?")
print("12")

¿Qué fue lo más interesante que encontré en los datos?
Me sorprendió que el año 2004 tuviera el Metacritic promedio más alto. Esto sugiere que fue una época dorada para los videojuegos. A pesar que los juegos de ahora son mejores en diseño, pero tal vez no tienen esa nostalgia que los de antes sí.

¿Qué género o plataforma te sorprendió más y por qué?
Me sorprendió que PC superara a PS5 en rating promedio (4.83 vs 4.72), esperaba que PS5 tuviera los mejores títulos por ser más moderna. Aparte que la PC no está hecho directamente para jugar, algo que la PS5 sí

¿Qué otra pregunta le harías a esta API si tuvieras más tiempo?
Me gustaría analizar si los juegos con más reseñas tienen mejor rating, o si hay alguna relación sobre el precio del juego y su reseña.

¿Cuántas requests usé en total?
12